# Generated by Django 3.2.9 on 2022-02-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstablequaterly',
            old_name='Specifications',
            new_name='specifications',
        ),
    ]
