# Generated by Django 3.2.9 on 2022-02-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_specifications_productstablequaterly_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstableprimary',
            name='id',
        ),
        migrations.AlterField(
            model_name='productstableprimary',
            name='modelNumber',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
