# Generated by Django 3.2.9 on 2022-02-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20220201_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttable',
            name='isAccountNumber',
        ),
        migrations.RemoveField(
            model_name='paymenttable',
            name='isUpiFlg',
        ),
    ]
