# Generated by Django 3.2.9 on 2022-03-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_webcredentialstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='temporaryOrderStoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, default='', max_length=50)),
                ('deleveryAddressId', models.CharField(blank=True, default='', max_length=50)),
                ('selectedMode', models.CharField(blank=True, default='', max_length=50)),
                ('paymentModeId', models.CharField(blank=True, default='', max_length=50)),
                ('currentOrderList', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
