# Generated by Django 3.2.9 on 2022-02-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20220202_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocodes',
            old_name='maxMaximumPriceCriteria',
            new_name='maxSellingPriceCriteria',
        ),
    ]
