# Generated by Django 3.2.9 on 2022-02-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_rename_maxmaximumpricecriteria_promocodes_maxsellingpricecriteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hometable',
        ),
    ]
