# Generated by Django 3.2.9 on 2022-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_delete_hometable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordertable',
            name='orderItemId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
