# Generated by Django 3.2.9 on 2022-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_alter_userordertable_orderitemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttable',
            name='bankName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
