# Generated by Django 3.2.9 on 2022-03-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20220318_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryorderstoretable',
            name='accId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='temporaryorderstoretable',
            name='cvvOrUpi',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
