# Generated by Django 3.2.9 on 2022-02-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_paymenttable_bankname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userordertable',
            old_name='orderFirstPaymentmodeWithID',
            new_name='orderFirstPaymentID',
        ),
        migrations.RenameField(
            model_name='userordertable',
            old_name='orderSecondPaymentmodeWithID',
            new_name='orderSecondPaymentID',
        ),
    ]
