# Generated by Django 3.2.9 on 2022-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20220319_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='globleVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenPercentage', models.CharField(blank=True, default='', max_length=50)),
                ('tokenMinimumAmount', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
