# Generated by Django 3.2.9 on 2022-03-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_globlevariables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globlevariables',
            old_name='tokenMinimumAmount',
            new_name='minimumTotalCost',
        ),
    ]
