# Generated by Django 3.2.9 on 2022-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_rename_tokenminimumamount_globlevariables_minimumtotalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globlevariables',
            name='minimumTotalCost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globlevariables',
            name='tokenPercentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
