# Generated by Django 3.2.9 on 2022-03-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_globlevariables_deliverycharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globlevariables',
            old_name='deliveryCharge',
            new_name='deliveryChargePercentage',
        ),
    ]
