# Generated by Django 3.2.9 on 2022-03-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_rename_companyname_useraddressbook_locationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressbook',
            old_name='stateOrCounty',
            new_name='state',
        ),
    ]
