# Generated by Django 3.2.9 on 2022-03-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_rename_stateorcounty_useraddressbook_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressbook',
            old_name='countryOrRegion',
            new_name='country',
        ),
    ]
