# Generated by Django 3.2.9 on 2022-03-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0017_rename_countryorregion_useraddressbook_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressbook',
            old_name='streetAddress2',
            new_name='landmark',
        ),
    ]
