# Generated by Django 3.2.9 on 2022-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0020_usertable_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='typeOfUser',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
